version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-dev
    user: root
    ports:
      - "5676:5672"   # AMQP (Backend -> RabbitMQ)
      - "15672:15672" # Management (Browser)
      - "1883:1883"   # MQTT (Testes/IoT)
      - "15675:15675" # Web-MQTT (App Mobile via WebSocket)
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins

volumes:
  rabbitmq_data: